FROM nvidia/cuda:11.4.3-cudnn8-devel-ubuntu20.04

ARG DALLE_SIZE=mini

# set working directory
WORKDIR /app

# install pip
RUN apt-get update && apt-get install -y python3-pip

# install git
RUN apt-get install -y git

# update pip
RUN pip3 install --upgrade pip

## glid
ENV PATH="/root/miniconda3/bin:$PATH"
ARG PATH="/root/miniconda3/bin:$PATH"

RUN apt-get install -y wget && rm -rf /var/lib/apt/lists/*

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh 

RUN conda --version

COPY ./environment.yaml /app/environment.yaml

RUN conda env create -f environment.yaml
SHELL ["conda", "run", "-n", "ldm", "/bin/bash", "-c"]

# add requirements
COPY ./requirements.txt /app/requirements.txt

# install requirements
RUN pip3 install -r requirements.txt

# install jax[cuda]
RUN pip3 install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

# glid-3-xl models
RUN mkdir -p glid_models

RUN wget https://dall-3.com/models/glid-3-xl/bert.pt -O glid_models/bert.pt \
    && wget https://dall-3.com/models/glid-3-xl/kl-f8.pt -O glid_models/kl-f8.pt \
    && wget https://dall-3.com/models/glid-3-xl/finetune.pt -O glid_models/finetune.pt

# SwinIR model
#RUN mkdir -p swinir_model
#RUN wget https://github.com/JingyunLiang/SwinIR/releases/download/v0.0/001_classicalSR_DF2K_s64w8_SwinIR-M_x8.pth -O swinir_model/swinir.pth
#RUN wget https://github.com/JingyunLiang/SwinIR/releases/download/v0.0/003_realSR_BSRGAN_DFOWMFC_s64w8_SwinIR-L_x4_GAN.pth -O swinir_model/swinir.pth

# add source code
COPY . /app

# Model specific config
RUN cp model_config_${DALLE_SIZE}.yaml model_config.yaml

CMD celery --app celery_tasks_dalle.celery worker --loglevel=info 2>&1 | tee logs.txt
