FROM nvidia/cuda:11.4.3-cudnn8-devel-ubuntu20.04

ARG DALLE_SIZE=mini

# set working directory
WORKDIR /app

# install pip
RUN apt-get update && apt-get install -y python3-pip

# install git
RUN apt-get install -y git

# update pip
RUN pip3 install --upgrade pip

## glid
ENV PATH="/root/miniconda3/bin:$PATH"
ARG PATH="/root/miniconda3/bin:$PATH"

RUN apt-get install -y wget && rm -rf /var/lib/apt/lists/*

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh 

RUN conda --version

COPY ./environment_sdm.yaml /app/environment_sdm.yaml

RUN conda env create -f environment_sdm.yaml
SHELL ["conda", "run", "-n", "llama_dalle", "/bin/bash", "-c"]

# SwinIR model
#RUN mkdir -p swinir_model
#RUN wget https://github.com/JingyunLiang/SwinIR/releases/download/v0.0/001_classicalSR_DF2K_s64w8_SwinIR-M_x8.pth -O swinir_model/swinir.pth
#RUN wget https://github.com/JingyunLiang/SwinIR/releases/download/v0.0/003_realSR_BSRGAN_DFOWMFC_s64w8_SwinIR-L_x4_GAN.pth -O swinir_model/swinir.pth

# add source code
COPY . /app

# Model specific config
RUN cp model_config_${DALLE_SIZE}.yaml model_config.yaml

CMD celery --app celery_tasks_dalle.celery worker --loglevel=info 2>&1 | tee logs.txt
