name: llama_flask
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.5
  - pip=21.2.4
  - numpy=1.19.2
  - pip:
    - albumentations==0.4.3
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - celery==5.2.3
    - redis==4.1.4
    - Flask==2.1.0
    - Flask-Cors==3.0.9
    - Flask-RESTful==0.3.8
    - gunicorn
